# Generated by Django 2.0 on 2019-09-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='votes_total',
        ),
    ]
